### PR TITLE
extend IPluginRegistry with movePluginsTop

### PR DESCRIPTION
**Pull request by gotcha**

### CODE REVIEW

**Review by dataflake — APPROVED** [review]

**Comment by dataflake** [comment]
Don't forget to forward-port to master.

**Comment by gotcha** [comment]
Thanks for merging. Would you give me permission to release on Pypi (userid gotcha) ?

**Comment by dataflake** [comment]
You have it now

**Comment by gotcha** [comment]
@dataflake Thanks

**Pull request merged**
